# SITE CONFIGURATION
baseurl: # the subpath of your site, e.g. /blog/
url: "http://stereobooster.github.io" # the base hostname & protocol for your site

exclude:
  - 'node_modules'
  - 'bin'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'

github:
  repository_url: "https://github.com/stereobooster/stereobooster.github.io"
  repository_name: "stereobooster.github.io"
  owner_name: "stereobooster"

# jekyll-seo-tag
# title - Your site's title (e.g., Ben's awesome site, The GitHub Blog, etc.)
# description - A short description (e.g., A blog dedicated to reviewing cat gifs)
# url - The full URL to your site. Note: site.github.url will be used by default.
# author - global author information (see below)
twitter:
  username: stereobooster
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
# logo - URL to a site-wide logo (e.g., /assets/your-company-logo.png)
# social - For specifying social profiles. The following properties are available:
# name - If the user or organization name differs from the site's name
# links - An array of links to social media profiles.
# google_site_verification for verifying ownership via Google webmaster tools

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "stereobooster blog"
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: >
   I'm a passionate developer and technical esthete in search of truth and wisdom on software development.
   This is my blog and notepad. I want it to be something as solid as codinghorror. But it also can contain some reminders to myself and code snippets.

  # Header and footer text
  header_text: >
   <p>I'm a passionate developer and technical esthete in search of truth and wisdom on software development.</p>
   <p>This is my blog and notepad. I want it to be something as solid as codinghorror. But it also can contain some reminders to myself and code snippets.</p>
  header_text_feature_image:
  footer_text:

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "stereobooster"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-23660048-1"
  disqus_shortname: "stereobooster"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  # google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

permalink: :title

# PAGINATION
paginate: 20
paginate_path: "blog/page:num"

excerpt_separator: "\n\n\n"

# BUILD SETTINGS
sass:
  sass_dir: _sass
  style: :compressed

# markdown: kramdown
# kramdown:
#   input: GFM
#   auto_ids: true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

markdown: redcarpet
redcarpet:
  extensions: ['tables', 'autolink', 'strikethrough', 'space_after_headers', 'with_toc_data', 'fenced_code_blocks']

highlighter: pygments
# pygments_options: ['lineanchors']

gems:
  - jekyll-seo-tag
  # - jekyll-typogrify
  # - jekyll-compose
  # - jekyll-mentions
  # - jemoji
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed
