safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:     /

destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   /:title

url: http://method67.com
author: stereobooster
site_name: 67-й метод

# breadcrumbs:
  # name: ---------✂---------
  # url: "/#main"

apis:
  google_analytics_uid: UA-23778458-1
  addthis_uid: ra-4f032ec338067ecc
  disqus_shortname: method67
  yandex_metrika_uid: 11889496

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

